### ISSUE TITLE
"A good string implementation" and UTF-8-only implementations

### ISSUE THREAD

**Issue by sunfishcode** [wingo/stringrefs#22]
The stringref proposal has a goal to "Provide a good string implementation that many languages implemented on top of the GC proposal would find useful."

Does this proposal envision source languages that need 16-bit code units and unpaired surrogates build their string types directly on top of this `stringref` proposal?

This proposal also has as a requirement "Allow UTF-8-only implementation for non-web WebAssembly implementations".

If such source languages come to depend on `stringref` cursors being 16-bit code-unit indices and unpaired surrogates being accepted and preserved, does that mean those languages would be expected to be incompatible with UTF-8-only implementations?

**Comment by wingo** [comment]
> Does this proposal envision source languages that need 16-bit code units and unpaired surrogates build their string types directly on top of this `stringref` proposal?

This is a very good question, thank you for asking it.  I don't know the answer.

This is a matter of interpretation, but I don't think any language *needs* unpaired surrogates -- they usually indicate bugs or invalid input.  Some programs have bugs though, and some program input is invalid.  If this were just one program or one input then sure, I would expect that e.g. Kotlin would use `stringref` at some level -- it is OK to break that one program.  If it all Kotlin programs needed unpaired surrogates, then no I would think this proposal isn't useful to them.  I am not sure what Kotlin would decide here.

If Kotlin (just as an example) decides to use stringref and also expects to be able to do `str[n]` even for low surrogates in well-formed UTF-16, then as-is I would expect a Kotlin string to be a `stringref` with breadcrumbs.  Even if you know you are compiling for the web (your toolchain emits JS, so you know already that a cursors is a UTF-16 code unit offset), you still need to access low surrogates in a funny way (effectively picking apart the result of `String.prototype.getCodePointAt`).

We could change to allow cursors on UTF-16 systems to point to the low surrogate of a surrogate pair.  That would make it so that Kotlin wouldn't need breadcrumbs on the web but would need them on a UTF-8 target.  See #10.

> This proposal also has as a requirement "Allow UTF-8-only implementation for non-web WebAssembly implementations".
> 
> If such source languages come to depend on `stringref` cursors being 16-bit code-unit indices and unpaired surrogates being accepted and preserved, does that mean those languages would be expected to be incompatible with UTF-8-only implementations?

The proposal as it stands cannot create strings with unpaired surrogates.  `string.new` can only create from `one-byte`, `utf-8`, and `utf-16`.  If a program has unpaired surrogates, they come from the host -- so these programs are already not portable.

So we are left with the incompatibility of hosts reasoning about cursor values rather than using `string.advance` et al.  Two ways this could happen -- the cursor value comes from the host (e.g. JavaScript computed a code unit offsets), in which case the program is already not portable.  Or the WebAssembly itself is computing cursor values -- yes, that's an interop risk.  I think it is manageable but I appreciate your thoughts here!

Finally, going back to CLR/JVM languages that like to think of strings in terms of UTF-16 code units: there are some natural synergies with the JS platform here regarding strings that you wouldn't automatically get with a UTF-8-only host.  JS implementations already have to make UTF-16 code unit lookup fast (even if they switched to UTF-8 under the hood; #21).  If I were wasmtime and I liked UTF-8, I wouldn't want to make `stringref` include a breadcrumbs facility for UTF-16 access, unless it were absolutely needed.  So is it needed?  Do we need to specify a way to index `stringref` by UTF-16 code unit offset, or is it sufficient to leave to the language implementation?  I lean towards making it the language implementation's responsibility but I really don't know!

**Comment by wingo** [comment]
A couple more comments here -- generally speaking I expect that language implementations will want to inline their loops over strings.  I expect this to happen via `string.encode` to a specific encoding, which could be UTF-16, and then you work on those code units.  Inlining per-code-unit work is more important that avoiding a copy.  Using UTF-8 for `stringref` contents poses no problem for this use case.

Also, it would be possible to add API to advance a string cursor in UTF-16 code units, regardless of the underlying representation.  e.g.

```
string.advance_utf16 str:stringref cur:i32 units:i32
-> new-cur:i32, unit:i32
```
Advance the string cursor *cur* by *units* code units.  Return the resulting cursor.  Because there is one cursor position per codepoint, but some codepoints require two code units, also return a unit index, indicating which code unit this cursor position corresponds to.  This unit index is one if the code unit that would be *units* code units ahead of the string position *cur* is a low surrogate of a surrogate pair, and zero otherwise.

**Comment by skuzmich** [comment]
> This is a matter of interpretation, but I don't think any language needs unpaired surrogates -- they usually indicate bugs or invalid input.

Languages need unpaired surrogates because there is value in backwards compatibility and not a lot of good reasons to get rid of them. Perhaps a good string implementation shouldn't force languages to break their semantics.

> If Kotlin (just as an example) decides to use stringref and also expects to be able to do `str[n]` even for low surrogates in well-formed UTF-16, then as-is I would expect a Kotlin string to be a stringref with breadcrumbs.

Breadcrumbs looks like a trick for supporting some old API which is planned to be phased out. Many languages have `str[n]` (usually UTF-16 code units or UTF-8 bytes) and don't consider changing it in the future. Perhaps a good string implementation should allow languages to keep their fundamental APIs efficient.

**Comment by sunfishcode** [comment]
I believe my questions here are sufficiently answered for now. Clearly there are still open questions, but they're getting discussed as part of other issues.
