### ISSUE TITLE
UTF-8 requirement?

### ISSUE THREAD

**Issue by sunfishcode** [wingo/stringrefs#28]
The proposals's README.md currently lists this as a Requirement:

> 3. Allow UTF-8-only implementation for non-web WebAssembly implementations

Is this still considered a requirement? If so, how would this work, with the proposal's motion toward explicit WTF?

**Comment by wingo** [comment]
@sunfishcode I think that it needs to be updated to say "Allow WebAssembly implementations to efficiently represent strings internally in either WTF-8 or WTF-16 encodings".

In the initial proposal I was thinking that unpaired surrogates only came from a JavaScript host, and that WebAssembly implementations that weren't paired with JavaScript would thereby be able to live in a USV-sequence world if they chose to do so.  But after talking with source language people I think that it's clear they can come from source programs too -- say, a Java program that processes a string's code units in chunks, which could split a surrogate pair.

It's a shame because isolated surrogates are quite rare; consider that both Emscripten and wasm-bindgen have been mangling them for years and nobody complains.  But if we relaxed and allowed e.g. non-web implemetations to trap on isolated surrogates, that would introduce strange behavior differences between web and non-web.

WDYT?

**Comment by sunfishcode** [comment]
Changing it to WTF, as #33 does, does indeed make this section consistent with the other changes.

It seemed like earlier versions of the proposal implied that languages such as Java might use their own string representation, that might use `stringref` internally, but would be able to do other things too. My impression from the recent changes is that that approach is no longer being pursued, and the new approach seems to be to have `stringref` just be Java's string representation, with `concat`, `slice`, and possibly more features over time as well. Does that sound like what you're expecting?

**Comment by wingo** [comment]
@sunfishcode yeah that is what I am expecting.  These are just such a gnarly bunch of tradeoffs as you know but in the end it boiled down to "how important is it for webassembly + gc + stringref to support languages like java/scala/kotlin/c#/f#".  I think the implications of the previous requirements were that we didn't have a very good story there, and weighing that against requiring non-JS wasm implementations to make a string type that supports isolated surrogates, I ended up being convinced more by the WTF argument.  It wasn't so much because of the web platform, but rather because of the kinds of languages that would usefully target stringref.  Without WTF stringrefs, Java et al would pay a higher penalty when accessing host facilities and when passing strings across to other component-model components.
