### ISSUE TITLE
Strings as a new Web + WASI API?

### ISSUE THREAD

**Issue by tlively** [wingo/stringrefs#43]
I think that having a standard low-level, language-agnostic string API is a great idea, but I'm not convinced (yet) that the Wasm Core spec is the best place for it. IMO, proposals should extend the core spec's semantics only when their objectives cannot be reasonably achieved higher in the stack, and I still think it's possible that we could satisfy this proposal's requirements with externref + imports, as long as those imports are the API from this proposal rather than "whatever JS String does."

The explainer currently provides three reasons why using externref + imports is insufficient:

#### On platform expressivity:

> if the strings feature required some capability from the host, then it would be clearly best as a library.

I don't think strings being pure compute is a good reason to prefer to put them in the core spec. Lots of libraries are pure compute.

> [strings] are closer to the GC proposal; although you could implement structs and arrays via externref and imports, if you did that you might as well compile to JavaScript instead of WebAssembly.

GC data layout and access is a cross-cutting concern for the entire compilation scheme of a language. In contrast, specific data structures can be implemented via imports without affecting the big picture of how a program is compiled, so I'm not sure this argument applies to strings.

> It should be possible to make a WebAssembly program that uses reference-typed strings (because almost all such programs would have strings) without relying on any JavaScript at all.

Any interesting program is going to rely on host imports for _something_, so why not for strings as well? This proposal is all about interoperability with the host's implementation of strings, after all.

> Also, the evolutionary endpoint of an externref-and-imports strategy is a JavaScript-specific string interface... This is not a good platform outcome.

That's why I think this proposal is important. We should absolutely standardize a more universally useful string API, but that doesn't imply putting it in Core, either. Developing a single API for both WASI and the Web will ensure ecosystem-wide availability.

#### On performance:

> 1. Whereas an externref might need to be a tagged union, a stringref can be an unpacked pointer.

My understanding is that `externref` (aka `anyref`) is not represented any differently than a normal JS object on Web engines and would have the same representation as `stringref`.

> 3. ...more predictable performance than e.g. an encoder implemented in JS (for web embeddings).
>
> 4. Reading string contents, either via string.encode_wtf8-then-process-inline or via stringview_wtf16, is likely faster than calling out to JavaScript to read code units one at a time. WebAssembly-to-JavaScript calls are cheap but not free.

With a new Web API, engines would still implement all the operations as builtins just like they would if strings were in Core, so none of the functionality would need to be implemented in JS. I would hope engines could make crossing the boundary from the Wasm to the builtin string operations fast.

> 2. WebAssembly instructions are likely faster and less of an optimization barrier than callouts to imports.

I suspect this is the most important argument for having strings in Core, but I would want to see how far we could get with reliable engine optimizations of imported builtins first.

#### On security:

> adding stringref to WebAssembly removes a significant user of extra-module access to memory.

Maybe, but the host has access to your memory anyways and if you care about isolation from other Wasm modules, you're probably using some intermediate layer like interface types and having strings in Core won't help.

**Comment by lars-t-hansen** [comment]
@tlively,

> #### On performance:
> 
> > 1. Whereas an externref might need to be a tagged union, a stringref can be an unpacked pointer.
> 
> My understanding is that `externref` (aka `anyref`) is not represented any differently than a normal JS object on Web engines and would have the same representation as `stringref`.

I don't think this is necessarily true.  In SpiderMonkey currently, an externref is always a JSObject*; anything that comes in that is not a JSObject* is boxed in an externref box.  But this is known to be insufficient; at a minimum externref will become a tagged pointer to express (JSObject*|JSString*), since a JSString is not a JSObject in SpiderMonkey, a string has a specialized representation and currently we're boxing a string into a JSObject* at the boundary, a pointless expense.  It is also attractive to allow small integers to be represented directly without incurring a boxing on entry to wasm.  Anyway, in this representation we might, if we could get away with it, represent a stringview as a JSString* and the externref wrapping the stringview would be subject to at least tagging and untagging.

> > 3. ...more predictable performance than e.g. an encoder implemented in JS (for web embeddings).
> > 4. Reading string contents, either via string.encode_wtf8-then-process-inline or via stringview_wtf16, is likely faster than calling out to JavaScript to read code units one at a time. WebAssembly-to-JavaScript calls are cheap but not free.
> 
> With a new Web API, engines would still implement all the operations as builtins just like they would if strings were in Core, so none of the functionality would need to be implemented in JS. I would hope engines could make crossing the boundary from the Wasm to the builtin string operations fast.

Since you envision the builtins being expressed as imports, I think that means you're also interested in intrinsic/privileged imports; otherwise, any call to an import will want to be compiled as a fairly expensive context switch, as the module compilation cannot anticipate the imports that the module will be instantiated with.  To be sure, an import call is much cheaper than a JS call, but it still seems quite expensive compared to inlinable code.

I'm not at all opposed to experimenting with externref and imports to handle stringrefs, but it would be useful to flesh out both approaches in some detail to see where the costs differ in the different engines.

**Comment by wingo** [comment]
Yeah this is a very interesting question.  I think the proposal would benefit from a comparison to a library polyfill, and if the polyfill were good enough, that would be a good result.

While I'm digesting this, two observations:

1. As the Dart-to-JS people mentioned on Tuesday, it would be nice to have constant-expression strings, so as to be able to have immutable globals with constant GC datastructures that include strings.  I am not sure how to achieve this without instruction-level support.
2. Consider a module A that wants to call `(string.new_wtf8 $memory ptr:address bytes:i32) -> str:stringref`.  If you made this an import instead of an instruction, the import would have to be specific to a module A's memory -- i.e. you wouldn't have just one common library that implements this functionality, you'd need to separately instantiate that library with module A's memory as an import.  This might in turn require module A to import its memory, even if it's the "main" module which knows how much memory to allocate.  Does this sound right to you @tlively or am I making a mistaken assumption somewhere?

**Comment by tlively** [comment]
Thanks for those details, @lars-t-hansen!

> Since you envision the builtins being expressed as imports, I think that means you're also interested in intrinsic/privileged imports...

With lazy compilation, I'm envisioning that the inlining of imports could be an implementation detail and not require spec changes. But the spec design has always assumed an eager compilation model, so maybe requiring lazy compilation for good string performance is not good and we would want to introduce compile-time imports in the spec.

> I'm not at all opposed to experimenting with externref and imports to handle stringrefs, but it would be useful to flesh out both approaches in some detail to see where the costs differ in the different engines.

+1 for fleshing out both approaches to see how much of a win built-in `stringref` actually is (both in terms of performance and spec simplicity).

@wingo,

> As the Dart-to-JS people mentioned on Tuesday, it would be nice to have constant-expression strings, so as to be able to have immutable globals with constant GC datastructures that include strings. I am not sure how to achieve this without instruction-level support.

Talking with @askeska-google offline, it turns out that Dart's particular use case of const initializers would be satisfied by imported globals containing JS strings, but I agree it would be nice to be able to declare static string data inside a module. If we allowed calling imports in global initializers, composing the segment-to-array instruction from GC with an array-to-string import might work. I don't know how much appetite there would be for allowing that, though.

Good point about the API needing to have a handle to a specific Wasm memory. I hadn't considered that, and that does seem like a complicated problem to solve.

**Comment by lars-t-hansen** [comment]
> Thanks for those details, @lars-t-hansen!
> 
> > Since you envision the builtins being expressed as imports, I think that means you're also interested in intrinsic/privileged imports...
> 
> With lazy compilation, I'm envisioning that the inlining of imports could be an implementation detail and not require spec changes. But the spec design has always assumed an eager compilation model, so maybe requiring lazy compilation for good string performance is not good and we would want to introduce compile-time imports in the spec.

@tlively, Indeed I have a strong bias against lazy compilation / reoptimization and similar tricks for wasm.  I know we may need some of these mechanisms to handle some modern OO languages well, but (a) that's unresolved and (b) stringref feels like a fairly basic feature and really ought not depend on a heavy-weight implementation mechanism for good performance.

**Comment by wingo** [comment]
Continuation: https://github.com/WebAssembly/stringref/issues/8
